on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19.1', '1.19.3' ]
    name: Go ${{ matrix.go }} Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Run Tests
        run: go test ./... -v
